#!/bin/sh
GITUSER="$1"
eval set -- $SSH_ORIGINAL_COMMAND
# $1 = command
# $2 = repo path
REPO="$2"
if [ -d "$REPO" ] && [ -r "$REPO"/.users ]; then
  if grep -q "^$GITUSER\$" "$REPO"/.users; then
    eval "$@"
  else
    echo "Error: $GITUSER not authorized on $REPO" >&2
  fi
else
  eval "$@"
fi
